# Generated by Django 3.2.5 on 2021-08-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('access_token', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('SNcode', models.CharField(max_length=300)),
            ],
        ),
    ]
