# Generated by Django 3.1 on 2021-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='dinggroup',
            name='SNcode',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dinggroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
